"""Evidence shared by the Analyst and the Reporter, built deterministically from state.

References are numbered here once, so both agents cite the same [n], and the reference list
and dataset table in the report are generated by code (accurate, no LLM formatting loops)."""
from __future__ import annotations

from ..state import ResearchState

MIN_RELEVANCE = 0.3


def ref_papers(state: ResearchState) -> list:
    """[(n, paper, verdict)] for relevant papers, most relevant first."""
    # iterate in paper order + stable sort, so ties get the same numbers as in the UI's Analysis tab
    pv = state.paper_verdicts
    rows = sorted(((pv[p.id], p) for p in state.papers if p.id in pv and pv[p.id].relevance >= MIN_RELEVANCE),
                  key=lambda r: -r[0].relevance)
    return [(i + 1, p, v) for i, (v, p) in enumerate(rows)]


def papers_evidence(state: ResearchState) -> str:
    lines = []
    for n, p, v in ref_papers(state):
        hl = " ".join(f'"{h.quote}"' for h in v.highlights)
        lines.append(f"[{n}] {p.title} ({', '.join(p.authors[:3])}, {p.year}) relevance={v.relevance}\n"
                     f"    abstract: {p.abstract[:900]}\n    judge: {v.value_added} | findings: {'; '.join(v.key_findings)}"
                     + (f"\n    quotes: {hl}" if hl else ""))
    return "\n".join(lines) or "No relevant papers were found."


def datasets_evidence(state: ResearchState) -> str:
    ds = {d.id: d for d in state.datasets}
    lines = [f"- {ds[k].title} ({ds[k].source}) usefulness={v.usefulness} covers={', '.join(v.covered_features) or 'none'}; {v.notes}"
             for k, v in sorted(state.dataset_verdicts.items(), key=lambda kv: -kv[1].usefulness)
             if k in ds and v.usefulness >= MIN_RELEVANCE]
    return "\n".join(lines) or "No suitable datasets were found."


def references_md(state: ResearchState) -> str:
    refs = ref_papers(state)
    if not refs:
        return "## References\n\n_No relevant papers were found._"
    lines = ["## References", ""]
    for n, p, _ in refs:
        authors = ", ".join(p.authors[:3]) + (" et al." if len(p.authors) > 3 else "")
        lines.append(f"[{n}] {authors} ({p.year or 'n.d.'}). *{p.title}*. {p.url}  ")
    return "\n".join(lines)


def _cell(text: str, n: int = 180) -> str:
    text = " ".join(str(text).split()).replace("|", "/")
    return text if len(text) <= n else text[:n] + "..."


def dataset_table(state: ResearchState) -> str:
    ds = {d.id: d for d in state.datasets}
    rows = sorted(((v, ds[k]) for k, v in state.dataset_verdicts.items() if k in ds and v.usefulness >= MIN_RELEVANCE),
                  key=lambda r: -r[0].usefulness)
    if not rows:
        return "_No suitable datasets were found._"
    lines = ["| Dataset | Source | Usefulness | Covers features | Used for |", "|---|---|---|---|---|"]
    for v, d in rows:
        lines.append(f"| [{_cell(d.title, 80)}]({d.url}) | {d.source} | {round(v.usefulness * 100)}% | "
                     f"{_cell(', '.join(v.covered_features) or '-', 80)} | {_cell(v.used_for)} |")
    return "\n".join(lines)
