"""Agent 4 - Reporter: writes (and later edits) the markdown research report.

The report is problem-first and synthesized (built on the Analyst's ProblemAnalysis), not a
paper-by-paper list. The dataset table and the numbered references are generated by code."""
from __future__ import annotations

import re

from langchain_core.messages import HumanMessage, SystemMessage

from ..activity import emit
from ..export import clean_markdown
from ..llm import get_llm, text_of, thoughts_of
from ..state import ResearchState
from .material import dataset_table, datasets_evidence, papers_evidence, references_md
from .researcher import _brief_text

TABLE_MARK = "{{DATASET_TABLE}}"

# Placeholder structure - replace with the official report format when it is available.
REPORT_FORMAT = f"""# <Project title>
## 1. The Problem
(what the problem is, why it matters, who is affected, what people are trying to fix)
## 2. What Has Been Done So Far
(a synthesis of prior work organized by theme/approach, with [n] citations: what the field has
achieved and where it falls short - never a paper-by-paper list)
## 3. Critical Assessment of the Proposed Project
(is the topic well-defined, feasible and novel? hidden assumptions, risks, data and evaluation concerns)
## 4. Open Gaps and Where You Can Contribute
(concrete contribution angles: what, why it is still open, feasibility, data needed)
## 5. Recommended Direction
(refined scope, refined research questions, suggested methodology, baselines and metrics)
## 6. Candidate Datasets
{TABLE_MARK}
(then 1-2 sentences of notes per important dataset, as bullets)"""

SYSTEM = f"""You are the Reporter agent. Write a critical research report in Markdown for a student,
built on the Analyst's analysis and the evidence provided.

Writing rules:
- Problem first: the reader must understand the problem before any literature.
- Summarize what was previously done as a SYNTHESIS of the field, grouped by approach. Do NOT
  write "Paper X did this. Paper Y did that." Write e.g. "Most existing systems rely on ... [1][3],
  which achieves ... but struggles with ... [2]."
- Cite only with the reference numbers [n] given. Do not write a References section - the system
  appends it. Never invent papers, numbers, results or quotes.
- Be critical and honest: if the topic is vague, too broad, infeasible or largely solved, say so
  clearly and explain what would make it workable.
- Never write Markdown tables yourself: write the line {TABLE_MARK} exactly once where the dataset
  table goes - the system inserts it.

Use this format:

{REPORT_FORMAT}"""

MIN_SECTIONS = 6  # "## " sections the LLM must write; fewer means the output was cut off


def _analysis_text(state: ResearchState) -> str:
    a = state.analysis
    if a is None:
        return "No analysis available."
    themes = "\n".join(f"- {t.name}: {t.synthesis}" for t in a.state_of_the_art)
    opps = "\n".join(f"- {o.title} (feasibility {o.feasibility}, data available: {o.data_available}): "
                     f"{o.description} Why open: {o.why_open}" for o in a.contribution_opportunities)
    return (f"PROBLEM: {a.problem_statement}\nWHY IT MATTERS: {a.why_it_matters}\n"
            f"WHAT PEOPLE TRY TO FIX: {'; '.join(a.what_people_try_to_fix)}\n"
            f"STATE OF THE ART (themes):\n{themes}\n"
            f"LIMITATIONS OF CURRENT WORK: {'; '.join(a.limitations_of_current_work)}\n"
            f"TOPIC ASSESSMENT: {a.topic_assessment} - {a.assessment_reasoning}\n"
            f"CRITICAL CONCERNS: {'; '.join(a.critical_concerns)}\n"
            f"CONTRIBUTION OPPORTUNITIES:\n{opps}\n"
            f"REFINED SCOPE: {a.refined_scope}\nREFINED RESEARCH QUESTIONS: {'; '.join(a.refined_research_questions)}\n"
            f"SUGGESTED METHODOLOGY: {a.suggested_methodology}\nANALYST CONFIDENCE: {a.confidence}")


def _material(state: ResearchState) -> str:
    scope_note = ""
    if state.scope_decision == "keep" and state.analysis and state.analysis.topic_assessment != "well_defined":
        scope_note = "\nNOTE: the student chose to KEEP their original scope despite the Analyst's concerns.\n"
    return (f"PROJECT BRIEF\n{_brief_text(state)}\n{scope_note}\n"
            f"ANALYST'S CRITICAL ANALYSIS\n{_analysis_text(state)}\n\n"
            f"NUMBERED PAPERS (cite as [n])\n{papers_evidence(state)}\n\n"
            f"USEFUL DATASETS\n{datasets_evidence(state)}\n\nJUDGE GAPS: {state.gaps}")


def _finalize(text: str, state: ResearchState) -> str:
    """Insert the code-built dataset table and references into the LLM's text."""
    # drop tables / reference sections the LLM wrote anyway (incl. runaway |:---- separator lines)
    text = "\n".join(l for l in text.splitlines() if not l.lstrip().startswith("|"))
    text = re.sub(r"-{12,}", "---", text)
    text = re.split(r"^#+ *References\s*$", text, flags=re.M | re.I)[0].rstrip()
    table = "\n\n" + dataset_table(state) + "\n\n"
    if TABLE_MARK in text:
        text = text.replace(TABLE_MARK, table, 1).replace(TABLE_MARK, "")
    else:  # fall back: right after the datasets heading, or at the end
        m = re.search(r"^## *\d+\. *Candidate Datasets.*$", text, flags=re.M)
        text = text[:m.end()] + "\n\n" + table + text[m.end():] if m else text + "\n\n" + table
    text = re.sub(r"\n{3,}", "\n\n", text).rstrip()
    return text + "\n\n" + references_md(state) + "\n"


def _strip_generated(report: str, state: ResearchState) -> str:
    """Inverse of _finalize, so the editor LLM never has to reproduce the table or references."""
    report = report.replace(dataset_table(state), TABLE_MARK)
    report = re.sub(r"\n{3,}", "\n\n", report)
    return re.split(r"^## References\s*$", report, flags=re.M)[0].rstrip()


def _write(messages) -> tuple[str, dict]:
    """Invoke the LLM and validate the report; retry up to 3 times if it was cut off,
    keeping the most complete attempt. Returns (report, info for the state log)."""
    best, info = "", {}
    for attempt in range(1, 4):
        emit("reporter", "status", "Writing the report…" if attempt == 1
             else f"The output looked incomplete - rewriting (attempt {attempt})")
        msg = get_llm(thoughts=True).invoke(messages)
        if thought := thoughts_of(msg):
            emit("reporter", "thought", thought)
        text = clean_markdown(text_of(msg))
        finish = str(msg.response_metadata.get("finish_reason") or msg.response_metadata.get("stop_reason") or "")
        sections = sum(1 for line in text.splitlines() if line.startswith("## "))
        if len(text) > len(best):
            best, info = text, {"attempts": attempt, "finish_reason": finish, "sections": sections}
        if sections >= MIN_SECTIONS and finish.upper() in ("STOP", "END_TURN", ""):
            break
    if not best:
        raise RuntimeError("The LLM returned an empty report")
    emit("reporter", "decision", f"Report written: {info['sections']} sections, {len(best):,} characters")
    return best, info


def reporter_node(state: ResearchState) -> dict:
    text, info = _write([SystemMessage(SYSTEM), HumanMessage(_material(state))])
    return {
        "report_markdown": _finalize(text, state),
        "report_version": state.report_version + 1,
        "phase": "report_review",
        "log": [{"node": "reporter", "report_version": state.report_version + 1, **info}],
    }


SECTION_SYSTEM = ("You edit ONE section of a Markdown research report. Apply the user's instruction to this "
                  "section only and return the full updated section, starting with its heading line. Keep [n] "
                  "citations, do not invent sources, never write Markdown tables.")


def split_sections(report: str) -> list[str]:
    """Split a report into chunks that each start at a '## ' heading (the first chunk is the title part)."""
    parts = re.split(r"(?m)^(?=## )", report)
    return [p for p in parts if p]


def _edit_section(state: ResearchState) -> tuple[str, dict] | None:
    """Edit only the requested section and splice it back; None if the section is not found."""
    report = _strip_generated(state.report_markdown or "", state)
    parts = split_sections(report)
    wanted = state.pending_section.lstrip("#").strip().lower()
    idx = next((i for i, p in enumerate(parts) if p.startswith("## ") and wanted in p.splitlines()[0].lower()), None)
    if idx is None:
        return None
    emit("reporter", "status", f"Editing only the section '{parts[idx].splitlines()[0].lstrip('# ')}'")
    msg = get_llm().invoke([SystemMessage(SECTION_SYSTEM), HumanMessage(
        f"INSTRUCTION: {state.pending_instruction}\n\nSOURCE MATERIAL\n{_material(state)}\n\nSECTION\n{parts[idx]}")])
    new_section = clean_markdown(text_of(msg)).strip()
    if not new_section.startswith("## "):
        new_section = parts[idx].splitlines()[0] + "\n" + new_section
    parts[idx] = new_section + "\n\n"
    emit("reporter", "decision", "Section updated; the rest of the report is unchanged")
    return "".join(parts), {"section": parts[idx].splitlines()[0]}


def report_editor_node(state: ResearchState) -> dict:
    if state.pending_section and (edited := _edit_section(state)):
        text, info = edited
        return {
            "report_markdown": _finalize(text, state),
            "report_version": state.report_version + 1,
            "pending_instruction": None, "pending_section": None,
            "log": [{"node": "report_editor", "report_version": state.report_version + 1, **info}],
        }
    text, info = _write([
        SystemMessage("You edit a Markdown research report. Apply the user's instruction and return the "
                      "FULL updated report in Markdown only. Keep it a synthesis (not paper-by-paper), keep "
                      f"[n] citations, do not invent sources, keep the line {TABLE_MARK} unchanged, never "
                      "write Markdown tables, and do not add a References section (the system appends it)."),
        HumanMessage(f"INSTRUCTION: {state.pending_instruction}\n\nSOURCE MATERIAL\n{_material(state)}\n\n"
                     f"CURRENT REPORT\n{_strip_generated(state.report_markdown or '', state)}"),
    ])
    return {
        "report_markdown": _finalize(text, state),
        "report_version": state.report_version + 1,
        "pending_instruction": None, "pending_section": None,
        "log": [{"node": "report_editor", "report_version": state.report_version + 1, **info}],
    }
